# Generated by Django 5.1 on 2024-09-12 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.BigIntegerField()),
                ('cvv', models.IntegerField()),
                ('fecha_ano', models.PositiveIntegerField()),
                ('fecha_mes', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminuser.user')),
            ],
        ),
    ]
