# Generated by Django 5.1 on 2024-09-13 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0002_tarjeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='apodo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
