# Generated by Django 5.1 on 2024-09-13 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0003_tarjeta_apodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='mv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=100)),
                ('tarjeta', models.CharField(max_length=20)),
                ('cantidad', models.BigIntegerField()),
                ('fecha', models.DateField()),
                ('tipo', models.TextField(max_length=20)),
                ('estado', models.TextField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminuser.user')),
            ],
        ),
    ]
